spring.application.name=sb-ecom
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
project.images=images
image.base.url=http://localhost:8080/images/
jwt.expiration=3000000
payu.merchant.key=97jY0s
payu.merchant.salt=WRBsskQbBjF1ZK5Vq7FxZslDM5DKcyy5

cashfree.id=TEST10810982214fd4145fe5e77449b028901801
cashfree.secret=cfsk_ma_test_69822116409bde393ccee6aea2c4d785_30355d95

#Redis Configuration
spring.data.redis.host=redis-18002.crce283.ap-south-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=18002
spring.data.redis.username=default
spring.data.redis.password=YUDqwkdYl7r1FaH1ifmj3xPWbXaksCvv

#SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shopease.india.official@gmail.com
spring.mail.password=wuxc jgmy oigi orad
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#MultiPart File Size Limit
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

#Cloudinary Configuration
cloudianry.config.name=dnnavziyx
cloudianry.config.key=556628461518837
cloudianry.config.secret=MNqXse-XWvjZ92Tf_Tq0anI3Rvc
