spring.application.name=sb-ecom
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
jwt.expiration=${JWT_EXPIRATION}
refreshtoken.expiration=${REFRESH_TOKEN_EXPIRATION}
jwt.secret=${JWT_SECRET}
#spring.jpa.show-sql=true
project.images=images
image.base.url=http://localhost:8080/images/
payu.merchant.key=${PAYU_KEY}
payu.merchant.salt=${PAYU_SALT}

frontend.url=${FRONTEND_URL}

#Cashfree Configuration
cashfree.id=${CASHFREE_ID}
cashfree.secret=${CASHFREE_SECRET}

#Redis Configuration
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

#SMTP Configuration
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#MultiPart File Size Limit
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

#Cloudinary Configuration
cloudinary.config.name=${CLOUDINARY_CONFIG_NAME}
cloudinary.config.key=${CLOUDINARY_CONFIG_KEY}
cloudinary.config.secret=${CLOUDINARY_CONFIG_SECRET}
